const cropsName = ["artichoke", "arugula", "asparagus", "basil", "beans", "beets", "bokchoy", "broccoli", "brussel", "cabbage", "carrots", "cauliflower", "celery", "chard", "cilantro", "corn", "cucumber", "eggplant", "fava", "garlic", "kale", "leek", "lettuce", "melon", "mustard", "okra", "onion", "parsley", "peas", "pepper", "potato", "pumpkin", "radish", "spinach", "squash", "watermelon", "tomato", "turnip", "zucchini"]


plantData = {
    "artichoke": document.write("PREPARING THE GARDEN <br/><br/> The artichoke is a perennial,/ so prepare the soil well before planting. Mix manure, compost, or other organic matter into the first foot of soil in about equal volumes.<br/><br/>Artichokes don't reproduce true from seed, so they're best planted by using root divisions available at nurseries. Or a healthy plant can be dug up, the root divided into two or more parts and replanted. Artichoke plants reach a height of 3 or 4 feet and a spread of up to 6 feet in diameter, so allow plenty of space for them to grow. In the vegetable garden, plant them to the side so that they won't be disturbed by the more frequent planting of annual vegetables. They should be spaded at intervals of 4 to 6 feet along the row with 6 to 8 feet between the rows. In the ornamental garden, don't plant them near tree roots, as they don't compete well for nutrients and water.</br> The root sections should be set 6 to 8 inches deep in the soil.<br/><br/> Irrigate thoroughly before planting."),
    "arugula": document.write("Growing Guide<br/><br/>Prefers rich humusy soil with pH of 6 to 6.8, but will tolerate wide variety of conditions. Evenly moist soil will help slow bolting.<br/> Growth is low and compact until heat causes plant to bolt. <br/> Forms a rosette of deeply lobed leaves. Plants become erect when heat induces bolting.<br/>Flowers are edible <br/><br/> MAINTAINING <br/>Seeds germinate quickly even in cold soil. Plant as soon as soil can be worked in spring.<br/>Avoid planting after other cabbage family crops.<br/> Plant ¼ inch deep and 1 inch apart in rows, or broadcast alone or mixed with other greens. Gradually thin to 6-inch spacings using thinnings for salads.<br/> Make new plantings every 2 to 3 weeks for a continuous supply until about a month before your average first frost date."),
    "asparagus": document.write("Asparagus is a hardy perennial suited to USDA zones 2 to 8 and is native to western Europe. This perennial can remain viable for 10 to 20 years, so choose your garden site carefully. Asparagus needs a soil pH of between 7.0 and 7.2 in fertile, well-draining soil. <br/><br/> There’s no trick to growing asparagus from seeds, just be patient. It’s recommended that you start asparagus seeds indoors or in a greenhouse in mid-February to May under bright lighting. Soil temperatures for seed germination should be between 70 and 85 degrees F. (21-29 C.). Soak the seeds for a couple of hours, then plant each seed ½ inch (1 cm.) deep in sterile soil, in individual 2 inch (5 cm.) pots. They should sprout anywhere between two and eight weeks from planting asparagus seeds."),
    "basil": document.write("Growing Guide <br/><br/> Needs 6 at least 6 hours of sun per day. <br/> Prefers steady moisture and warm soil. <br/><br/> Maintaining <br/> Plant basil in fertile soil in a spot that gets direct sun for at least 6 hours per day. Pinch the tip from the center shoot of basil after it has grown for 6 weeks to force side growth and prevent early flowering. If flower stalks develop, simply snip them off. Basil needs a steady supply of moisture and warm soil temperatures to produce well, so you have to play a balancing act with mulch. In cool areas, delay mulching until the soil temperature has reached the mid-60s. Where summer really heats up and soil loses moisture quickly, you can add mulch sooner. <br/> Basil has few pests, but occasionally generalist pests such as aphids, flea beetles, and Japanese beetles will feast upon it. Rinse off aphids with a garden hose. To prevent beetles from munching, cover the crop with fabric row cover. If slugs are a problem on new transplants, try a barrier of copper flashing."),
    ""
}